shell.setPath(shell.path()..":/bin")
dofile('/lib/env.lua')
dofile('/lib/funcs.lua')
dofile('/lib/promise.lua')
dofile('/lib/fhttp.lua')
dofile('/lib/bezosmapsapi.lua')
dofile('/lib/homeassistantapi.lua')
dofile('/lib/turtleapi.lua')